### PR TITLE
tab to switch between the location of a shipment and the location of this shipments pallets

### PR DESCRIPTION
**Pull request by finnstue**
The feature has an error. The width of the map that is supposed to show the pallets is too small.
Bildschirmfoto 2022-06-09 um 02 29 37
Bildschirmfoto 2022-06-09 um 02 29 40

### CODE REVIEW

**Comment by finnstue** [comment]
Also another thing: When the show page first loads the map is not scaled correctly to fit the markers. This changes after reloading, but would be good to fix
Bildschirmfoto 2022-06-09 um 02 30 02

Bildschirmfoto 2022-06-09 um 02 29 52

**Comment by dumboluzz** [comment]
Looks good! But I'm not sure Arbi will allow this today. BTW: the size of the pallets map fixes itself if you resize the window. So I guess that will be hard to fix.

**Comment by JonNorman** [comment]
@finnstue in your PR description is the first image _after_ your fix and is the second image _before_? Just checking I know what I'm looking at!

**Comment by JonNorman** [comment]
image

I'm running this locally, but I'm not seeing the pallets when I switch tabs, just a blank white space. The map appears to be there, but the style is missing `active` which means that it has `display: none` applied. Comparing this to the shipments, where `active` is present as a style, I see the map (as it overrides the `display: none` and uses `display: block`).

Am I missing something?

image

**Comment by finnstue** [comment]
@dumboluzz Could you review this?

**Review by dumboluzz — APPROVED** [review]
Looks good to me!

I'm not sure why you force pushed all the changes from master into here, but it works!
Next time to get the changes from master just merge your branch into the updated master, then the pull request will just to a fast forward merge.

BTW the website looks weird on mobile, but I think that is not a priority right now.

**Comment by finnstue** [comment]
Thanks! The force push was because I had some issues with Github and had to change the way I connect my terminal to GH.

Optimizing for mobile needs to done at some point, you're very right.

**Pull request merged**
